classifier_app/config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'

  get    'sessions/new'
  get    'users/new'


  get    '/create',  to: 'classifier_request#create'
  post   '/create',  to: 'classifier_request#create'
  get    '/request', to: 'classifier_request#req'
  get    '/result',  to: 'classifier_request#result'


  get    '/help',     to: 'static_pages#help'
  get    '/about',    to: 'static_pages#about'
  get    '/contact',  to: 'static_pages#contact'
  get    '/download', to: 'static_pages#down'
  get    '/users/:id',to: 'users#show'
  get    '/signup',   to: 'users#new'
  post   '/signup',   to: 'users#create'
  post   '/del',      to: 'users#del'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  
  get "*any", via: :all, to: 'application#page_not_found'

  resources :users

end

classifier_app/app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

classifier_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <!--
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
  -->
  <center>
    <%= link_to image_tag("tutor.png", alt:"Book Logo", width: 64, height: 64), 'https://www.railstutorial.org/book' %>
    &nbsp
    <%= link_to image_tag("rails.png", alt: "Rails logo", width: 64, height: 64), 'http://rubyonrails.org/' %>
    &nbsp
    <%= link_to image_tag("caffe.png", alt: "Caffe Logo", height: 64), 'http://caffe.berkeleyvision.org/' %>
    &nbsp
    <%= link_to image_tag("alexnet.png", alt: "Alexnet Logo", height: 64), 'https://en.wikipedia.org/wiki/AlexNet' %>
    &nbsp
    <%= link_to image_tag("gtu.png", alt:"GTU Logo", width: 64, height: 64), 'http://www.gtu.edu.tr' %>
  </center>


</footer>

classifier_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      <%= link_to "Cloud Classifier", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if classifier_running? %>
          <%= image_tag("greendot.png", alt:"GTU Logo", width: 20, height: 20) %>
        <% else %>
          <%= image_tag("reddot.png", alt:"GTU Logo", width: 20, height: 20) %>
        <% end %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About",  about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <!--<li><%= link_to "Help", help_path %></li>-->
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <!--<li><%= link_to "Settings", '#' %></li> -->
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

classifier_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

classifier_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag 'cl.png' %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>